---
- name: Ansible - GIT - Jenkins 
  hosts: node1
  tasks:
   - name: Say HELLO world
     command: echo "Hello worldi version3 - integration with Git"
     register: output
   - debug:
      var: output
